server.port=${PORT:8080}

spring.data.mongodb.uri=mongodb+srv://AvvasHomeFoods_db_user:avvashomefoods2026@cluster0.tzaxssa.mongodb.net/avvahomefoods

spring.application.name=avva-home-foods
google.client.id=${GOOGLE_CLIENT_ID}
